#!/usr/bin/env bash
# Write apps/web/.env.local from production CloudFormation outputs so `vite dev`
# can open watch-party rooms against the hosted control plane.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${ROOT}/apps/web/.env.local"
AWS_REGION="${AWS_REGION:-us-east-1}"
# Same default as infra/cdk/README.md operator commands.
AWS_PROFILE="${AWS_PROFILE:-me}"
ORIGIN="${VITE_DEV_ORIGIN:-http://localhost:5173}"
MEDIA="remote"
PRINT_ONLY=0

API_STACK="${API_STACK:-RiffSyncApi-prod}"
FAN_AUTH_STACK="${FAN_AUTH_STACK:-RiffSyncFanAuth-prod}"
STAFF_AUTH_STACK="${STAFF_AUTH_STACK:-RiffSyncStaffAuth-prod}"

usage() {
  cat <<'EOF'
Write apps/web/.env.local from production CloudFormation outputs.

Usage:
  scripts/dev/write-web-env-from-prod.sh [--profile me] [--media remote|local] [--origin URL] [--print]

Options:
  --profile NAME  AWS CLI profile (default: me, or AWS_PROFILE if set).
  --media remote  Use prod SFU from the sfu-token (default). Rooms, chat, and media hit AWS.
  --media local   Override SFU to ws://127.0.0.1:3000 (requires npm run media:local).
  --origin URL    Local Vite origin for OAuth/share links (default http://localhost:5173).
  --print         Print the file to stdout instead of writing .env.local.

Needs AWS CLI credentials that can describe RiffSyncApi-prod, RiffSyncFanAuth-prod,
and RiffSyncStaffAuth-prod. Region defaults to us-east-1.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      AWS_PROFILE="${2:-}"
      shift 2
      ;;
    --media)
      MEDIA="${2:-}"
      shift 2
      ;;
    --origin)
      ORIGIN="${2:-}"
      shift 2
      ;;
    --print)
      PRINT_ONLY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ "${MEDIA}" != "remote" && "${MEDIA}" != "local" ]]; then
  echo "--media must be remote or local" >&2
  exit 1
fi

if [[ -z "${AWS_PROFILE}" ]]; then
  echo "--profile must be a non-empty AWS CLI profile name" >&2
  exit 1
fi

if ! command -v aws >/dev/null 2>&1; then
  echo "aws CLI is required (https://docs.aws.amazon.com/cli/)" >&2
  exit 1
fi

# Env access keys override --profile and are a common source of InvalidClientTokenId.
aws_cli() {
  env -u AWS_ACCESS_KEY_ID -u AWS_SECRET_ACCESS_KEY -u AWS_SESSION_TOKEN -u AWS_SECURITY_TOKEN \
    aws --profile "${AWS_PROFILE}" --region "${AWS_REGION}" "$@"
}

if [[ -n "${AWS_ACCESS_KEY_ID:-}" || -n "${AWS_SESSION_TOKEN:-}" ]]; then
  echo "Ignoring AWS_ACCESS_KEY_ID / AWS_SESSION_TOKEN in this shell so profile ${AWS_PROFILE} is used." >&2
fi

echo "Reading production stacks in ${AWS_REGION} with profile ${AWS_PROFILE}…" >&2
if ! aws_cli sts get-caller-identity >/dev/null; then
  echo "Profile ${AWS_PROFILE} is not authenticated. Try: aws sso login --profile ${AWS_PROFILE}" >&2
  echo "Or refresh keys: aws configure --profile ${AWS_PROFILE}" >&2
  exit 1
fi

stack_out() {
  local stack="$1"
  local key="$2"
  local value
  if ! value="$(aws_cli cloudformation describe-stacks \
    --stack-name "${stack}" \
    --query "Stacks[0].Outputs[?OutputKey=='${key}'].OutputValue" \
    --output text)"; then
    echo "DescribeStacks failed for ${stack} (${AWS_REGION}, profile ${AWS_PROFILE})" >&2
    exit 1
  fi
  if [[ -z "${value}" || "${value}" == "None" ]]; then
    echo "Missing CloudFormation output ${key} on ${stack} (${AWS_REGION})" >&2
    exit 1
  fi
  printf '%s' "${value}"
}

API_BASE="$(stack_out "${API_STACK}" HttpApiUrl)"
API_BASE="${API_BASE%/}"
WS_URL="$(stack_out "${API_STACK}" WebSocketUrl)"
FAN_DM_WS_URL="$(stack_out "${API_STACK}" FanDmWebSocketUrl)"
COGNITO_BASE="$(stack_out "${FAN_AUTH_STACK}" FanHostedUiBaseUrl)"
COGNITO_DOMAIN="${COGNITO_BASE#https://}"
COGNITO_CLIENT="$(stack_out "${FAN_AUTH_STACK}" FanUserPoolClientId)"
COGNITO_POOL="$(stack_out "${FAN_AUTH_STACK}" FanUserPoolId)"
COGNITO_REGION="${COGNITO_POOL%%_*}"
STAFF_COGNITO_BASE="$(stack_out "${STAFF_AUTH_STACK}" StaffHostedUiBaseUrl)"
STAFF_COGNITO_DOMAIN="${STAFF_COGNITO_BASE#https://}"
STAFF_COGNITO_CLIENT="$(stack_out "${STAFF_AUTH_STACK}" StaffUserPoolClientId)"

SFU_LINE="# VITE_PUBLIC_SFU_WS_URL is unset so POST /v1/webrtc/sfu-token supplies the prod signal host."
if [[ "${MEDIA}" == "local" ]]; then
  SFU_LINE="VITE_PUBLIC_SFU_WS_URL=ws://127.0.0.1:3000"
fi

BODY="$(cat <<EOF
# Generated by scripts/dev/write-web-env-from-prod.sh — do not commit.
# Restart \`npm run dev\` after regenerating.

VITE_PUBLIC_ORIGIN=${ORIGIN}
VITE_PUBLIC_API_BASE_URL=${API_BASE}
VITE_PUBLIC_WS_URL=${WS_URL}
VITE_PUBLIC_FAN_DM_WS_URL=${FAN_DM_WS_URL}
VITE_COGNITO_HOSTED_UI_DOMAIN=${COGNITO_DOMAIN}
VITE_COGNITO_CLIENT_ID=${COGNITO_CLIENT}
VITE_COGNITO_USER_POOL_ID=${COGNITO_POOL}
VITE_COGNITO_REGION=${COGNITO_REGION}
VITE_STAFF_COGNITO_HOSTED_UI_DOMAIN=${STAFF_COGNITO_DOMAIN}
VITE_STAFF_COGNITO_CLIENT_ID=${STAFF_COGNITO_CLIENT}
VITE_CAST_RECEIVER_APP_ID=77E78672
${SFU_LINE}
EOF
)"

if [[ "${PRINT_ONLY}" -eq 1 ]]; then
  printf '%s\n' "${BODY}"
  exit 0
fi

mkdir -p "$(dirname "${OUT}")"
printf '%s\n' "${BODY}" > "${OUT}"
echo "Wrote ${OUT}" >&2
echo "Next: cd apps/web && npm run dev" >&2
if [[ "${MEDIA}" == "local" ]]; then
  echo "Local SFU: npm run media:local && curl -sSf http://127.0.0.1:3000/healthz" >&2
  echo "Copy riffsync/sfu-join-hmac-secret into infra/local-media/.env as SFU_JWT_SECRET." >&2
fi
